const GET_SOURCES_REQUEST = "GET_SOURCES_REQUEST";
const GET_SOURCES_SUCCESS = "GET_SOURCES_SUCCESS";
const GET_SOURCES_FAIL = "GET_SOURCES_FAIL";

const GET_NEWSLIST_REQUEST = "GET_NEWSLIST_REQUEST";
const GET_NEWSLIST_SUCCESS = "GET_NEWSLIST_SUCCESS";
const GET_NEWSLIST_FAIL = "GET_NEWSLIST_FAIL";

const SELECT_HEADLINE = "SELECT_HEADLINE";

const ADD_FAV = "ADD_FAV";
const REMOVE_FAV = "REMOVE_FAV";

export {
  GET_SOURCES_FAIL,
  GET_SOURCES_REQUEST,
  GET_SOURCES_SUCCESS,
  GET_NEWSLIST_REQUEST,
  GET_NEWSLIST_SUCCESS,
  GET_NEWSLIST_FAIL,
  SELECT_HEADLINE,
  ADD_FAV,
  REMOVE_FAV,
};
